### PR TITLE
fix variable is_internal_disconnected errors

### PR DESCRIPTION
**Pull request by ckfear**
fix the issue #465

### CODE REVIEW

**Comment by troupmar** [comment]
Just ran into this today as well. Any progress on the merging process here? @leeway1208

**Comment by leeway1208** [comment]
> 

Hi troupmar, 😄 I tested the logic of calling the disconnect() method and it will not cause reconnection, unless mqtt!.autoReconnect = true is set, is there any difference on your side?

**Comment by troupmar** [comment]
Yes, that is right. However I do not assume the re-connection should happen (even when the autoReconnect is set to true) if I explicitly call the disconnect() method. It should only happen if the disconnection happens internally. Or am I missing something?

**Comment by leeway1208** [comment]
Haha got it, good idea, I will discuss with my colleagues. Thanks

**Pull request merged**
